apiVersion: v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  source:
    git:
      uri: https://github.com/luszczynski/custom-jenkins-ose-config.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-1-rhel7
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: jenkins:latest
